### ISSUE TITLE
this（ perisco/cmd/start/config.go） file need config？

### ISSUE THREAD

**Issue by k8svip** [KumKeeHyun/perisco#2]
I want use your code to deploy，but how to use es as exporter，how to config?

**Comment by KumKeeHyun** [comment]
I'm sorry I didn't fill out the document.

Configs can be passed as Env or command arguments.
(please see [perisco/cmd/root.go](https://github.com/KumKeeHyun/perisco/blob/main/perisco/cmd/root.go), [perisco/cmd/start/config.go](https://github.com/KumKeeHyun/perisco/blob/main/perisco/cmd/start/config.go))

key for exporter is 'exporter' and prefix is 'perisco'.
=> `PERISCO_EXPORTER=file` or `PERISCO_EXPORTER=elasticsearch`

defult exporter is file exporter.
you can set output file path through `PERISCO_EXPORTER_FILE_NAME=/path/of/file`
If path is not set, file exporter will export msg to STDOUT.

if you want to use elasticsearch exporter, you need to set more configs for elasticsearch client.
=> `PERISCO_EXPORTER_ELASTICSEARCH_ADDRESSES=https://localhost:9200,https://localhost:9201`
=> `PERISCO_EXPORTER_ELASTICSEARCH_USERNAME=foobar` 
=> ...

**Comment by k8svip** [comment]
The reason for the **difference** between the environment variables in the YAML file and the configuration file could be as follows:  


file:   perisco/install/kubernetes/perisco
/deployment.yml 

      - name: PERISCO_CIDRS
          value: 10.244.0.0/16 #,::FFFF:10.244.0.0/112
        - name: PERISCO_PROTOS
          value: HTTP/1
        - name: PERISCO_KUBERNETES
          value: 'true'



file:   perisco/perisco/cmd/start
/config.go 

func setFlags(flags *pflag.FlagSet) {
	// perisco protocols
	flags.String(keyCidrs, "0.0.0.0/0", "List of cidrs to monitor sevices")
	flags.String(keyProtos, "HTTP/1,HTTP/2", "List of protocols to parse[HTTP/1 | HTTP/2]")

	// kubernetes enricher
	flags.Bool(keyKubernetes, false, "Enable k8s resources enricher")
	flags.String(keyKubernetesMasterUrl, "", "Kubernetes master url")
	flags.String(keyKubernetesConfigPath, "", "Kubernetes kubeconfig path")

	// exporter
	flags.String(keyExporter, "file", "Exporter type[file | elasticsearch]. default: file")
	// exporter file
	flags.String(keyExporterFileName, "", "File exporter target file")
	flags.Bool(keyExporterFilePretty, false, "Enable pretty print")
	// exporter elasticsearch
	flags.String(keyExporterElasticsearchAddresses, "", "list of Elasticsearch nodes to use")
	flags.String(keyExporterElasticsearchUsername, "", "Username for HTTP Basic Authentication")
	flags.String(keyExporterElasticsearchPassword, "", "Password for HTTP Basic Authentication")
	flags.String(keyExporterElasticsearchCloudID, "", "Endpoint for the Elastic Service")
	flags.String(keyExporterElasticsearchAPIKey, "", "Base64-encoded token for authorization")
	flags.String(keyExporterElasticsearchServiceToken, "", "Service token for authorization")
	flags.String(keyExporterElasticsearchFingerprint, "", "fingerprint given by Elasticsearch on first launch")
}

**Comment by KumKeeHyun** [comment]
The defaults for config.go are based on use cases that are not used in the Kubernetes environment, and monitor all networks events(0.0.0.0/0) and output the generated logs to a file (stdout).

The yaml file is a configuration for deploying to my local kubernetes cluster

it specified podCIDRs (10.244.0.0/16) to monitor pod-pod communication only, and excluded HTTP/2 because the monitoring target was HTTP/1 only.
