### ISSUE TITLE
error：(MEMLOCK may be too low, consider rlimit.RemoveMemlock）

### ISSUE THREAD

**Issue by k8svip** [KumKeeHyun/perisco#3]
loading objects: field FentrySockRecvmsg: program fentry_sock_recvmsg: map server_map: map create: operation not permitted (MEMLOCK may be too low, consider rlimit.RemoveMemlock)

**Comment by KumKeeHyun** [comment]
To use ebpf, perisco must run in privileged mode.

if you use 'docker run', please add '--privileged' option.
if you use in kubernetes, it needs to set securityContext(CAP_SYS_ADMIN or ) in pod spec. [doc link](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/)

**Comment by k8svip** [comment]
thanks.

**Comment by KumKeeHyun** [comment]
Close
